---
Name: ecommerce_nutritional_products
Before: 'mysite/*'
After: 'framework/*','cms/*', 'ecommerce/*'
---


ProductGroup:
  extensions:
    - NutriHolderProductDataExtension

---
Only:
  classexists: 'ProductVariation'
---
ProductVariation:
  extensions:
    - NutriHolderProductDataExtension
